### ISSUE TITLE
Make sure tmux uses a 1-based index

### ISSUE THREAD

**Issue by kseistrup** [kseistrup/kbmsgr#1]
When tmux' index is zero-based, the lower window doesn't appear at all. Make sure the index is 1-based before calling split-window.

Thanks to @Musickiller for shining a light on that bug.

**Comment by Musickiller** [comment]
you wanted to add something to the app so that this would not be a problem. Done it? (I've created ~/.tmux.conf, but I would with pleasure delete it, if the bug is killed.) =D

**Comment by kseistrup** [comment]
You will know when the solution is incorporated in the app when this bug is closed. :wink:

**Comment by Musickiller** [comment]
OK =)
